# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2024 Leon Friedrich
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2025 DeusMaldPr
# SPDX-FileCopyrightText: 2025 ScarKy0
#
# SPDX-License-Identifier: MIT

- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  guides: [ Revolutionaries ]
  requirements:
<<<<<<< HEAD
  - !type:DepartmentTimeRequirement
    department: Security
    time: 3600 #1 hrs, klovn
=======
  - !type:OverallPlaytimeRequirement
    time: 1h
>>>>>>> upstream/master

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  guides: [ Revolutionaries ]

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
